Feature: Login Feature
Scenario: Login_Test Scenario
Given user is already on login page
When user enters username and password
Then user click on login button
And user click on new project
Then user click on internal no and porject name
And user click on Country and State/Province
And user click on City and Address
And user click on Bid.date and area
Then user click on next button
Then user click on multiple building classes and select education and daycare
And click on next button
Then click on finish